### ISSUE TITLE
\Hamjoint\Mustard\Auctions\Http\Controllers are missing

### ISSUE THREAD

**Issue by kolexndr** [hamjoint/mustard-auctions#1]
Hi,
vendor\hamjoint\mustard-auctions\src\includes\routes.php has references to
certain controllers, like InventoryController, ItemController, etc. under namespace Hamjoint\Mustard\Auctions\Http\Controllers,
but actually folder vendor\hamjoint\mustard-auctions\src\lib\  hasn't  Http/Controllers folder.

is this due to work in progress?

**Comment by tjbp** [comment]
Hi, yes this is due to WIP status - will commit this in shortly.

**Comment by kolexndr** [comment]
ok, thank you for your reply!

**Comment by tjbp** [comment]
These controllers are now tracked - though they may not be stable!

**Comment by kolexndr** [comment]
Thank you very much for update!
